/* ════════════════════════════════════════════
   PuzzleNet Verse — rooms.js
   32 puzzle-piece rooms, each a PuzzleNet service
   ════════════════════════════════════════════ */

// Puzzle piece connector types: N=north, S=south, E=east, W=west
// Each tab/blank defines how pieces interlock:
//   +1 = tab sticking OUT, -1 = blank going IN, 0 = flat edge (border)
// [N, E, S, W]

window.ROOMS = [
  /* ── ROW 0 ─────────────────────────────────────────────── */
  {
    id: 0, col: 0, row: 0,
    icon: '🛠', name: 'مرکز فرماندهی', service: 'PuzzleNet HQ',
    color: '#00d4ff', accent: '#0099bb',
    desc: 'قلب گروه فنی پازل‌نت — مدیریت پروژه، هماهنگی تیم و برنامه‌ریزی استراتژیک.',
    link: 'https://t.me/pazzle_net',
    tabs: [0, +1, +1, 0],   // N-flat(edge), E-tab, S-tab, W-flat(edge)
    chars: ['سروش — بنیان‌گذار','آریا — هوش مصنوعی'],
    objects: ['میز فرماندهی','صفحه نمایش بزرگ'],
  },
  {
    id: 1, col: 1, row: 0,
    icon: '🌐', name: 'زیرساخت شبکه', service: 'Network Infrastructure',
    color: '#00bfff', accent: '#0088aa',
    desc: 'طراحی و پیاده‌سازی شبکه‌های سازمانی، VLAN، روتینگ پیشرفته و مانیتورینگ.',
    link: 'https://t.me/pazzle_net',
    tabs: [0, +1, -1, -1],
    chars: ['علی — مهندس شبکه'],
    objects: ['سوییچ سیسکو','کابل‌کشی'],
  },
  {
    id: 2, col: 2, row: 0,
    icon: '🔥', name: 'فایروال و امنیت', service: 'Firewall & Security',
    color: '#ff4444', accent: '#cc2222',
    desc: 'پیکربندی OPNsense، pfSense، فایروال سازمانی و سیستم‌های IDS/IPS.',
    link: 'https://t.me/pazzle_net',
    tabs: [0, +1, +1, -1],
    chars: ['مریم — متخصص امنیت'],
    objects: ['فایروال سخت‌افزاری','کنسول مدیریت'],
  },
  {
    id: 3, col: 3, row: 0,
    icon: '📡', name: 'وایرلس و وایفای', service: 'Wireless Solutions',
    color: '#00ff88', accent: '#00bb66',
    desc: 'نصب و راه‌اندازی شبکه‌های وایرلس سازمانی، WiFi 6، mesh و کنترلر Unifi.',
    link: 'https://t.me/pazzle_net',
    tabs: [0, -1, +1, -1],
    chars: ['رضا — وایرلس انجینیر'],
    objects: ['اکسس پوینت Unifi','کنترلر وایرلس'],
  },

  /* ── ROW 1 ─────────────────────────────────────────────── */
  {
    id: 4, col: 0, row: 1,
    icon: '🖥', name: 'سرورهای HP', service: 'HP Server Solutions',
    color: '#ffd700', accent: '#cc9900',
    desc: 'فروش، نصب و پشتیبانی سرورهای HP ProLiant G9/G10 و راه‌اندازی iLO.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, +1, +1, 0],
    chars: ['رضا — سیستم‌آدمین'],
    objects: ['سرور HP G10','رک ۲۷U'],
  },
  {
    id: 5, col: 1, row: 1,
    icon: '☁', name: 'ابر و مجازی‌سازی', service: 'Cloud & Virtualization',
    color: '#87ceeb', accent: '#5599bb',
    desc: 'راه‌اندازی VMware، Hyper-V، Proxmox و مدیریت زیرساخت مجازی.',
    link: 'https://t.me/pazzle_net',
    tabs: [+1, -1, -1, -1],
    chars: ['نیلوفر — CloudOps'],
    objects: ['سرور مجازی','داشبورد ابری'],
  },
  {
    id: 6, col: 2, row: 1,
    icon: '💾', name: 'بکاپ و ذخیره‌سازی', service: 'Backup & Storage',
    color: '#ff8c00', accent: '#cc5500',
    desc: 'طراحی سیستم‌های بکاپ، NAS، SAN و بازیابی اطلاعات پس از فاجعه.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, +1, -1, +1],
    chars: ['سامان — ذخیره‌سازی'],
    objects: ['NAS Synology','دیسک‌های SAS'],
  },
  {
    id: 7, col: 3, row: 1,
    icon: '🔒', name: 'پازل‌نت گیت (VPN)', service: 'PuzzleNet Gate',
    color: '#00ff88', accent: '#00aa55',
    desc: 'فروش و مدیریت VPN اختصاصی با پرداخت ریالی و کریپتو از طریق ربات تلگرام.',
    link: 'https://t.me/puzzlenetgate_bot',
    tabs: [-1, 0, -1, -1],
    chars: ['ربات گیت 🔒'],
    objects: ['سرور VPN','پنل مدیریت'],
  },

  /* ── ROW 2 ─────────────────────────────────────────────── */
  {
    id: 8, col: 0, row: 2,
    icon: '🤖', name: 'هوش مصنوعی', service: 'AI & Machine Learning',
    color: '#8b5cf6', accent: '#6633cc',
    desc: 'پیاده‌سازی مدل‌های زبانی، چت‌بات هوشمند و اتوماسیون با AI محلی.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, -1, +1, 0],
    chars: ['آریا — هوش مصنوعی','کاوه — دیتاساینس'],
    objects: ['هسته LM Studio','GPU Server'],
  },
  {
    id: 9, col: 1, row: 2,
    icon: '⚡', name: 'اتوماسیون n8n', service: 'Workflow Automation',
    color: '#ff6b35', accent: '#cc4400',
    desc: 'طراحی گردش‌کارهای خودکار با n8n، ادغام API و اتوماسیون تلگرام.',
    link: 'https://t.me/pazzle_net',
    tabs: [+1, +1, +1, +1],
    chars: ['دارا — اتوماسیون'],
    objects: ['n8n Server','داشبورد گردش‌کار'],
  },
  {
    id: 10, col: 2, row: 2,
    icon: '🌍', name: 'وب و هاستینگ', service: 'Web & Hosting',
    color: '#00d4ff', accent: '#0099bb',
    desc: 'طراحی وب، هاستینگ اختصاصی، دامنه و مدیریت سرور VPS.',
    link: 'https://t.me/pazzle_net',
    tabs: [+1, -1, +1, -1],
    chars: ['پریسا — فرانت‌اند','امیر — بک‌اند'],
    objects: ['سرور Nginx','پنل cPanel'],
  },
  {
    id: 11, col: 3, row: 2,
    icon: '💸', name: 'پازل‌نت پی (کریپتو)', service: 'PuzzleNet Pay',
    color: '#ffd700', accent: '#cc9900',
    desc: 'درگاه پرداخت کریپتو با NowPayments — تتر، بیتکوین و ارزهای دیجیتال.',
    link: 'https://t.me/puzzlenetpay_bot',
    tabs: [+1, 0, -1, +1],
    chars: ['ربات پرداخت 💸'],
    objects: ['درگاه کریپتو','کیف پول دیجیتال'],
  },

  /* ── ROW 3 ─────────────────────────────────────────────── */
  {
    id: 12, col: 0, row: 3,
    icon: '🏠', name: 'خانه هوشمند', service: 'Smart Home',
    color: '#00ff88', accent: '#00aa55',
    desc: 'نصب و راه‌اندازی سیستم‌های خانه هوشمند، روشنایی، امنیت و اتوماسیون.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, +1, +1, 0],
    chars: ['آرش — اتوماسیون خانه'],
    objects: ['هاب هوشمند','سنسورها'],
  },
  {
    id: 13, col: 1, row: 3,
    icon: '📹', name: 'دوربین مداربسته', service: 'CCTV & Surveillance',
    color: '#ff4444', accent: '#cc2222',
    desc: 'نصب دوربین‌های IP، DVR، NVR و سیستم‌های نظارت تصویری.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, -1, -1, -1],
    chars: ['کامران — CCTV'],
    objects: ['NVR سامسونگ','دوربین‌های IP'],
  },
  {
    id: 14, col: 2, row: 3,
    icon: '🖨', name: 'تجهیزات اداری', service: 'Office Equipment',
    color: '#87ceeb', accent: '#4488aa',
    desc: 'فروش و سرویس پرینتر، اسکنر، UPS و تجهیزات جانبی اداری.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, +1, +1, +1],
    chars: ['نیما — تجهیزات'],
    objects: ['پرینتر لیزری','UPS APC'],
  },
  {
    id: 15, col: 3, row: 3,
    icon: '📱', name: 'موبایل و VoIP', service: 'Mobile & VoIP',
    color: '#8b5cf6', accent: '#5533aa',
    desc: 'راه‌اندازی سیستم تلفن تحت شبکه VoIP، سانترال IP و مدیریت تماس.',
    link: 'https://t.me/pazzle_net',
    tabs: [+1, 0, -1, -1],
    chars: ['شیرین — VoIP'],
    objects: ['سانترال IP','تلفن‌های SIP'],
  },

  /* ── ROW 4 ─────────────────────────────────────────────── */
  {
    id: 16, col: 0, row: 4,
    icon: '📥', name: 'پازل سیور (دانلود)', service: 'PuzzleNet Saver',
    color: '#ff6b35', accent: '#cc4400',
    desc: 'دانلود ویدیو از یوتیوب، اینستاگرام و سایر پلتفرم‌ها از طریق ربات تلگرام.',
    link: 'https://t.me/pazzlesaverbot',
    tabs: [-1, +1, +1, 0],
    chars: ['ربات سیور 📥'],
    objects: ['سرور دانلود','صف پردازش'],
  },
  {
    id: 17, col: 1, row: 4,
    icon: '🎵', name: 'پازل موزیک', service: 'PuzzleNet Music',
    color: '#ff69b4', accent: '#cc2277',
    desc: 'جستجو و دریافت موسیقی با هوش مصنوعی از طریق ربات تلگرام پازل‌نت موزیک.',
    link: 'https://t.me/puzzlenetmusic_bot',
    tabs: [-1, -1, -1, -1],
    chars: ['ربات موزیک 🎵'],
    objects: ['موتور جستجو','بانک موسیقی'],
  },
  {
    id: 18, col: 2, row: 4,
    icon: '📊', name: 'هوش تجاری (BI)', service: 'Business Intelligence',
    color: '#ffd700', accent: '#cc9900',
    desc: 'طراحی داشبوردهای تحلیلی، گزارش‌گیری هوشمند و تصمیم‌گیری مبتنی بر داده.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, +1, -1, +1],
    chars: ['سپیده — BI'],
    objects: ['داشبورد Power BI','سرور SQL'],
  },
  {
    id: 19, col: 3, row: 4,
    icon: '🛡', name: 'امنیت سایبری', service: 'Cybersecurity',
    color: '#00d4ff', accent: '#0077aa',
    desc: 'ارزیابی آسیب‌پذیری، تست نفوذ، آموزش امنیت و مشاوره ISMS.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, 0, +1, -1],
    chars: ['مریم — امنیت سایبری'],
    objects: ['ابزار Kali','سکنر Nessus'],
  },

  /* ── ROW 5 ─────────────────────────────────────────────── */
  {
    id: 20, col: 0, row: 5,
    icon: '🎓', name: 'آموزش IT', service: 'IT Training',
    color: '#00ff88', accent: '#009944',
    desc: 'دوره‌های آموزشی شبکه، امنیت، لینوکس و هوش مصنوعی برای تیم‌های سازمانی.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, -1, 0, 0],
    chars: ['استاد احمدی — آموزش'],
    objects: ['کلاس آنلاین','ماژول‌های آموزشی'],
  },
  {
    id: 21, col: 1, row: 5,
    icon: '🏢', name: 'راه‌اندازی استارتاپ', service: 'Startup Setup',
    color: '#8b5cf6', accent: '#5522aa',
    desc: 'راه‌اندازی زیرساخت IT برای استارتاپ‌ها — از صفر تا اولین سرور.',
    link: 'https://t.me/pazzle_net',
    tabs: [+1, -1, 0, +1],
    chars: ['نازنین — مشاوره'],
    objects: ['پلن استارتاپ','بوردروم'],
  },
  {
    id: 22, col: 2, row: 5,
    icon: '🔧', name: 'تعمیرات سخت‌افزار', service: 'Hardware Repair',
    color: '#ff8c00', accent: '#bb5500',
    desc: 'تعمیر سرور، لپ‌تاپ، تجهیزات شبکه و بازیابی داده از دیسک‌های خراب.',
    link: 'https://t.me/pazzle_net',
    tabs: [+1, +1, 0, -1],
    chars: ['داریوش — سخت‌افزار'],
    objects: ['میز تعمیر','ابزار الکترونیک'],
  },
  {
    id: 23, col: 3, row: 5,
    icon: '🌟', name: 'پازل‌نت توکن', service: 'PuzzleNet Token',
    color: '#ffd700', accent: '#cc9900',
    desc: 'توکن اختصاصی اکوسیستم پازل‌نت — جوایز، تخفیف و مزایای اعضا.',
    link: 'https://t.me/pazzle_net',
    tabs: [+1, 0, 0, +1],
    chars: ['سروش — توکن'],
    objects: ['بلاکچین','کیف پول توکن'],
  },

  /* ── ROW 6 (extra) ──────────────────────────────────────── */
  {
    id: 24, col: 0, row: 6,
    icon: '📺', name: 'یوتیوب پازل‌نت', service: 'YouTube Channel',
    color: '#ff0000', accent: '#aa0000',
    desc: 'کانال یوتیوب پازل‌نت — آموزش تکنولوژی به زبان ساده برای همه سنین.',
    link: 'https://t.me/pazzle_net',
    tabs: [+1, -1, 0, 0],
    chars: ['تیم محتوا'],
    objects: ['استودیو ضبط','میکروفون'],
  },
  {
    id: 25, col: 1, row: 6,
    icon: '📸', name: 'اینستاگرام', service: 'Instagram & Social',
    color: '#e1306c', accent: '#aa1144',
    desc: 'صفحه اینستاگرام پازل‌نت — محتوای تکنولوژی، پشت‌صحنه و اخبار جدید.',
    link: 'https://t.me/pazzle_net',
    tabs: [+1, +1, 0, +1],
    chars: ['ساناز — سوشیال'],
    objects: ['استودیو عکس','تجهیزات محتوا'],
  },
  {
    id: 26, col: 2, row: 6,
    icon: '⚙', name: 'DevOps', service: 'DevOps & CI/CD',
    color: '#00d4ff', accent: '#0088bb',
    desc: 'پیاده‌سازی CI/CD، Docker، Kubernetes و اتوماسیون استقرار نرم‌افزار.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, -1, 0, -1],
    chars: ['امیر — DevOps'],
    objects: ['Docker Host','Pipeline CI/CD'],
  },
  {
    id: 27, col: 3, row: 6,
    icon: '🎮', name: 'گیمینگ و محتوا', service: 'Gaming & Content',
    color: '#8b5cf6', accent: '#5522cc',
    desc: 'زیرساخت IT برای گیمرها — شبکه کم‌تاخیر، سرور بازی و ریگ گیمینگ.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, 0, 0, +1],
    chars: ['سروش — گیمر'],
    objects: ['ریگ گیمینگ','سرور بازی'],
  },

  /* ── ROW 7 (final) ──────────────────────────────────────── */
  {
    id: 28, col: 0, row: 7,
    icon: '🗄', name: 'دیتابیس و SQL', service: 'Database Solutions',
    color: '#00ff88', accent: '#00aa44',
    desc: 'طراحی، بهینه‌سازی و مدیریت پایگاه داده SQL Server، PostgreSQL و MongoDB.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, +1, 0, 0],
    chars: ['کاوه — DBA'],
    objects: ['سرور SQL','ابزار DBAtools'],
  },
  {
    id: 29, col: 1, row: 7,
    icon: '📧', name: 'میل سرور', service: 'Mail Server',
    color: '#87ceeb', accent: '#4477aa',
    desc: 'راه‌اندازی میل‌سرور اختصاصی با Zimbra یا Postfix، آنتی‌اسپم و آرشیو.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, +1, 0, -1],
    chars: ['آرمان — ایمیل'],
    objects: ['سرور Zimbra','فیلتر اسپم'],
  },
  {
    id: 30, col: 2, row: 7,
    icon: '🔗', name: 'API و یکپارچه‌سازی', service: 'API Integration',
    color: '#ff6b35', accent: '#cc3300',
    desc: 'توسعه و ادغام API، Webhook، ربات‌های تلگرام و اتصال سیستم‌های مختلف.',
    link: 'https://t.me/pazzle_net',
    tabs: [-1, -1, 0, -1],
    chars: ['پریسا — API Dev'],
    objects: ['Postman','داکیومنت API'],
  },
  {
    id: 31, col: 3, row: 7,
    icon: '🚀', name: 'آینده پازل‌نت', service: 'Future Zone — LOCKED',
    color: '#ffd700', accent: '#888800',
    desc: '🔮 این اتاق در نسخه‌های آینده پازل‌نت‌ورس باز خواهد شد. منتظر باشید...',
    link: 'https://t.me/pazzle_net',
    tabs: [+1, 0, 0, +1],
    locked: true,
    chars: ['؟؟؟'],
    objects: ['محتوای مخفی'],
  },
];
